# Generated by Django 4.2 on 2023-04-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'backlog',
            },
        ),
        migrations.CreateModel(
            name='GpuServerLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesstime', models.CharField(blank=True, db_column='accessTime', null=True)),
                ('response', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GPU_Server_Logs',
            },
        ),
        migrations.CreateModel(
            name='ModelPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(blank=True, null=True)),
                ('predicted_close', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'model_prediction',
            },
        ),
    ]
