# Generated by Django 4.2 on 2023-04-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroku_connection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backlog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gpuserverlogs',
            name='id',
        ),
        migrations.RemoveField(
            model_name='modelprediction',
            name='id',
        ),
        migrations.AlterField(
            model_name='backlog',
            name='ticker',
            field=models.CharField(default='DEFAULT_STOCK', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gpuserverlogs',
            name='accesstime',
            field=models.CharField(db_column='accessTime', default='0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modelprediction',
            name='stock',
            field=models.CharField(default='DEFAULT_STOCK', primary_key=True, serialize=False),
        ),
    ]
