# Generated by Django 4.2 on 2023-04-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroku_connection', '0002_remove_backlog_id_remove_gpuserverlogs_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='ticker',
            field=models.CharField(default='DEFAULT_STOCK', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gpuserverlogs',
            name='accesstime',
            field=models.CharField(db_column='accessTime', default='0', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gpuserverlogs',
            name='response',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modelprediction',
            name='stock',
            field=models.CharField(default='DEFAULT_STOCK', max_length=10, primary_key=True, serialize=False),
        ),
    ]
