# Generated by Django 4.2 on 2023-04-20 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroku_connection', '0003_alter_backlog_ticker_alter_gpuserverlogs_accesstime_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='backlog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='gpuserverlogs',
            table=None,
        ),
        migrations.AlterModelTable(
            name='modelprediction',
            table=None,
        ),
    ]
