# Generated by Django 4.2 on 2023-04-20 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroku_connection', '0004_alter_backlog_table_alter_gpuserverlogs_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backlog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gpuserverlogs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='modelprediction',
            options={'managed': False},
        ),
    ]
