# Generated by Django 4.2 on 2023-04-20 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroku_connection', '0005_alter_backlog_options_alter_gpuserverlogs_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='backlog',
            table='backlog',
        ),
        migrations.AlterModelTable(
            name='gpuserverlogs',
            table='GPU_Server_Logs',
        ),
        migrations.AlterModelTable(
            name='modelprediction',
            table='model_prediction',
        ),
    ]
