# Generated by Django 4.2 on 2023-04-08 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='receiver_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='sender_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='other_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
