# Generated by Django 4.1.7 on 2023-03-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradester', '0002_stock_portfolio_stock_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
