# Generated by Django 4.1.3 on 2023-03-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradester', '0002_stock_portfolio_stock_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='avg_daily_volume',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='beta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='earnings_per_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='high_52',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low_52',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price_to_earnings_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
