# Generated by Django 4.1.7 on 2023-03-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradester', '0003_investment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='id',
        ),
        migrations.AddField(
            model_name='investment',
            name='investment_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
