# Generated by Django 4.1.7 on 2023-03-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradester', '0004_alter_stock_avg_daily_volume_alter_stock_beta_and_more'),
        ('tradester', '0004_remove_investment_id_investment_investment_id'),
    ]

    operations = [
    ]
