# Generated by Django 4.1.7 on 2023-03-31 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradester', '0005_merge_20230315_1646'),
        ('tradester', '0005_merge_20230315_1732'),
    ]

    operations = [
    ]
