# Generated by Django 4.1.7 on 2023-03-31 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tradester', '0007_portfolio_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_stock',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
