# Generated by Django 4.1.7 on 2023-04-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradester', '0008_alter_portfolio_stock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
