# Generated by Django 4.2 on 2023-04-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradester', '0007_alter_stock_current_price_alter_stock_daily_high_and_more'),
        ('tradester', '0010_alter_portfolio_portfolio_id'),
    ]

    operations = [
    ]
