# Generated by Django 4.2 on 2023-04-04 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradester', '0013_alter_stock_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 19, 8, 59, 669593, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 19, 8, 59, 544621, tzinfo=datetime.timezone.utc)),
        ),
    ]
