# Generated by Django 4.2 on 2023-04-04 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tradester', '0014_alter_portfolio_stock_date_alter_stock_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_stock',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stock',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
