# Generated by Django 4.1.7 on 2023-04-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradester', '0016_rename_order_time_order_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='balance',
        ),
    ]
