# Generated by Django 4.2 on 2023-04-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradester', '0019_alter_order_order_type_alter_order_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('ticker', models.CharField(default='DEFAULT_STOCK', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'backlog',
                'db_table_comment': 'Heroku Table',
            },
        ),
        migrations.CreateModel(
            name='GpuServerLogs',
            fields=[
                ('accesstime', models.CharField(db_column='accessTime', default='0', primary_key=True, serialize=False)),
                ('response', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GPU_Server_Logs',
                'db_table_comment': 'Heroku Table',
            },
        ),
        migrations.CreateModel(
            name='ModelPrediction',
            fields=[
                ('stock', models.CharField(default='DEFAULT_STOCK', primary_key=True, serialize=False)),
                ('predicted_close', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'model_prediction',
                'db_table_comment': 'Heroku Table',
            },
        ),
        migrations.AlterModelTableComment(
            name='investment',
            table_comment='Render Table',
        ),
        migrations.AlterModelTableComment(
            name='order',
            table_comment='Render Table',
        ),
        migrations.AlterModelTableComment(
            name='portfolio',
            table_comment='Render Table',
        ),
        migrations.AlterModelTableComment(
            name='portfolio_stock',
            table_comment='Render Table',
        ),
        migrations.AlterModelTableComment(
            name='stock',
            table_comment='Render Table',
        ),
    ]
